# - Glob() adds all the files with the extension to the list
# - CPPPATH define the path where to look for source files which have include dependendcies
#		so that when these include files change, a recompilation of the source file is triggered
#		CPPPATH = ['include', '/home/project/inc']
#

env = Environment()
env.Decider("MD5")

ccmode = ARGUMENTS.get("MODE", "release")

if (ccmode == "DEBUG") | (ccmode == "debug"):
	env.Append(CPPFLAGS = ["-std=c++11", "-pedantic", "-Wall", "-pipe", "-g3", "-ggdb3", "-gstabs   3", "-DDEBUG"])
else:
	env.Append(CPPFLAGS = ["-std=c++11", "-pedantic", "-Wall", "-pipe", "-O3"])


env.Program('build/ser', Glob('*.cpp'), CPPPATH = '.')
env.Clean(".", "build")
